import type { Character, Project } from "@/lib/types";

function hashColor(input:string){let h=0;for(const c of input)h=(h*31+c.charCodeAt(0))>>>0;return `hsl(${h%360} 65% 58%)`;}
function animalType(c:Character){const s=`${c.name} ${c.appearance} ${c.role}`.toLowerCase();for(const a of ["lion","fox","bear","rabbit","bunny","cat","dog","mouse","elephant"])if(s.includes(a))return a;return "kid";}
function circle(ctx:CanvasRenderingContext2D,x:number,y:number,r:number,color:string){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function ellipse(ctx:CanvasRenderingContext2D,x:number,y:number,rx:number,ry:number,color:string){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function drawFace(ctx:CanvasRenderingContext2D,x:number,y:number,s:number,blink:boolean){circle(ctx,x-s*.18,y-s*.05,s*.045,"#111827");circle(ctx,x+s*.18,y-s*.05,s*.045,"#111827");if(!blink){circle(ctx,x-s*.17,y-s*.065,s*.014,"white");circle(ctx,x+s*.19,y-s*.065,s*.014,"white");}ctx.strokeStyle="#7c2d12";ctx.lineWidth=Math.max(2,s*.025);ctx.beginPath();ctx.arc(x,y+s*.1,s*.16,.2,Math.PI-.2);ctx.stroke();}
function drawCharacter(ctx:CanvasRenderingContext2D,c:Character,x:number,ground:number,scale:number,t:number,index:number){const type=animalType(c);const bob=Math.sin(t*4+index)*7*scale;const walk=Math.sin(t*5+index)*12*scale;const y=ground+bob;const body=hashColor(c.name);ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.lineCap="round";
  if(type==="lion"){circle(ctx,0,-132,57,"#b45309");circle(ctx,0,-132,42,"#f59e0b");circle(ctx,-31,-165,15,"#f59e0b");circle(ctx,31,-165,15,"#f59e0b");ellipse(ctx,0,-55,42,58,"#f59e0b");}
  else if(type==="fox"){ctx.fillStyle="#f97316";ctx.beginPath();ctx.moveTo(-38,-170);ctx.lineTo(-12,-138);ctx.lineTo(-48,-130);ctx.fill();ctx.beginPath();ctx.moveTo(38,-170);ctx.lineTo(12,-138);ctx.lineTo(48,-130);ctx.fill();circle(ctx,0,-130,40,"#f97316");ellipse(ctx,0,-52,38,56,"#f97316");ellipse(ctx,36,-38,18,48,"#fb923c");}
  else if(type==="rabbit"||type==="bunny"){ellipse(ctx,-18,-188,13,40,"#e5e7eb");ellipse(ctx,18,-188,13,40,"#e5e7eb");circle(ctx,0,-132,39,"#f3f4f6");ellipse(ctx,0,-53,37,56,"#e5e7eb");}
  else if(type==="bear"){circle(ctx,-30,-163,15,"#92400e");circle(ctx,30,-163,15,"#92400e");circle(ctx,0,-130,42,"#a16207");ellipse(ctx,0,-52,41,58,"#92400e");}
  else if(type==="cat"){ctx.fillStyle=body;ctx.beginPath();ctx.moveTo(-38,-165);ctx.lineTo(-15,-137);ctx.lineTo(-45,-130);ctx.fill();ctx.beginPath();ctx.moveTo(38,-165);ctx.lineTo(15,-137);ctx.lineTo(45,-130);ctx.fill();circle(ctx,0,-130,39,body);ellipse(ctx,0,-52,37,55,body);}
  else {circle(ctx,0,-140,36,"#f5c7a9");ellipse(ctx,0,-57,34,54,body);ctx.strokeStyle="#f5c7a9";ctx.lineWidth=15;ctx.beginPath();ctx.moveTo(-23,-78);ctx.lineTo(-45,-38+walk*.2);ctx.moveTo(23,-78);ctx.lineTo(45,-38-walk*.2);ctx.stroke();}
  drawFace(ctx,0,type==="kid"?-140:-132,38,Math.sin(t*2.6+index)>0.96);
  ctx.strokeStyle=type==="kid"?"#334155":body;ctx.lineWidth=16;ctx.beginPath();ctx.moveTo(-16,-18);ctx.lineTo(-22+walk,20);ctx.moveTo(16,-18);ctx.lineTo(22-walk,20);ctx.stroke();
  ctx.fillStyle="rgba(15,23,42,.78)";ctx.font="700 17px sans-serif";ctx.textAlign="center";ctx.fillText(c.name,0,52);ctx.restore();}
function drawEnvironment(ctx:CanvasRenderingContext2D,w:number,h:number,t:number,scene:number){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#60a5fa");g.addColorStop(.58,"#c4b5fd");g.addColorStop(1,"#fde68a");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
  const drift=(t*22)% (w+220);for(let i=0;i<4;i++){const x=(i*280+drift)-180;ellipse(ctx,x,90+i*32,72,22,"rgba(255,255,255,.72)");ellipse(ctx,x+48,82+i*32,52,25,"rgba(255,255,255,.72)");}
  ctx.fillStyle="#4ade80";ctx.beginPath();ctx.moveTo(0,h*.62);for(let x=0;x<=w;x+=80)ctx.lineTo(x,h*.62+Math.sin(x*.018+scene)*22);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();
  ctx.fillStyle="#16a34a";for(let i=0;i<7;i++){const x=55+i*150+Math.sin(t*.6+i)*10;ctx.fillRect(x,h*.58,12,90);circle(ctx,x+6,h*.56,40,"#22c55e");}
  circle(ctx,w-90,85,42,"#fde047");}
function drawScene(project:Project,canvas:HTMLCanvasElement,sceneIndex:number,sceneProgress:number,globalTime:number){const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas is unavailable on this browser.");const scene=project.scenes[Math.min(sceneIndex,project.scenes.length-1)];drawEnvironment(ctx,canvas.width,canvas.height,globalTime,sceneIndex);
  const ids=new Set(scene.characterIds);let chars=project.characters.filter(c=>ids.size===0||ids.has(c.id));if(!chars.length)chars=project.characters.slice(0,2);chars=chars.slice(0,3);
  const spacing=canvas.width/(chars.length+1);chars.forEach((c,i)=>{const entrance=Math.min(1,sceneProgress*2.2);const base=(i+1)*spacing;const from=i%2===0?-180:canvas.width+180;const x=from+(base-from)*entrance+Math.sin(globalTime*1.6+i)*10;drawCharacter(ctx,c,x,canvas.height*.79,.92,globalTime,i)});
  const fade=Math.min(1,sceneProgress*5)*Math.min(1,(1-sceneProgress)*5);ctx.fillStyle=`rgba(15,23,42,${.48*fade})`;ctx.fillRect(55,canvas.height-112,canvas.width-110,68);ctx.fillStyle=`rgba(255,255,255,${fade})`;ctx.font="700 25px sans-serif";ctx.textAlign="center";const caption=(scene.dialogue||scene.narration||scene.title).slice(0,92);ctx.fillText(caption,canvas.width/2,canvas.height-71);}
function recordVisuals(project:Project,canvas:HTMLCanvasElement,durationMs:number,audioTracks:MediaStreamTrack[]=[],onProgress?:(m:string)=>void){const stream=canvas.captureStream(30);const combined=new MediaStream([...stream.getVideoTracks(),...audioTracks]);const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm";const recorder=new MediaRecorder(combined,{mimeType:mime});const chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const start=performance.now();let frame=0;const draw=()=>{const elapsed=performance.now()-start;const ratio=Math.min(.999,elapsed/durationMs);const raw=ratio*project.scenes.length;const sceneIndex=Math.floor(raw);drawScene(project,canvas,sceneIndex,raw-sceneIndex,elapsed/1000);if(elapsed<durationMs)frame=requestAnimationFrame(draw)};return new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(new Error("Could not record the video."));recorder.onstop=()=>{cancelAnimationFrame(frame);stream.getTracks().forEach(t=>t.stop());resolve(new Blob(chunks,{type:mime}))};recorder.start(500);frame=requestAnimationFrame(draw);window.setTimeout(()=>{onProgress?.("Finalizing video…");if(recorder.state!=="inactive")recorder.stop()},durationMs+250)});}
async function renderWithDeviceVoice(project:Project,canvas:HTMLCanvasElement,onProgress?:(m:string)=>void){if(!("speechSynthesis" in window))throw new Error("This phone cannot run the free neural voice or Android narration.");const text=project.voiceLines.map(v=>v.text).join(" ")||project.story.fullStory;const words=text.trim().split(/\s+/).length;const duration=Math.max(6000,words/2.2*1000);const utterance=new SpeechSynthesisUtterance(text);utterance.lang="en-US";utterance.rate=.95;utterance.pitch=1.05;onProgress?.("Using Android narration…");window.speechSynthesis.cancel();window.speechSynthesis.speak(utterance);const blob=await recordVisuals(project,canvas,duration,[],onProgress);window.speechSynthesis.cancel();return blob;}
export async function renderNarratedVideo(project:Project,canvas:HTMLCanvasElement,onProgress?:(m:string)=>void){if(!canvas.captureStream||typeof MediaRecorder==="undefined")throw new Error("Video creation is not supported by this browser.");if(!project.scenes.length)throw new Error("This project has no scenes to render.");try{onProgress?.("Preparing free neural narration…");const{predict}=await import("@mintplex-labs/piper-tts-web");const text=project.voiceLines.map(v=>v.text).join(" ")||project.story.fullStory;const wav=await predict({text,voiceId:"en_US-hfc_female-medium"});const ac=new AudioContext();const buffer=await ac.decodeAudioData(await wav.arrayBuffer());const source=ac.createBufferSource();source.buffer=buffer;const dest=ac.createMediaStreamDestination();source.connect(dest);onProgress?.("Animating characters…");source.start();const blob=await recordVisuals(project,canvas,Math.max(1000,buffer.duration*1000),dest.stream.getAudioTracks(),onProgress);dest.stream.getTracks().forEach(t=>t.stop());await ac.close();return blob;}catch{return renderWithDeviceVoice(project,canvas,onProgress);}}
