import type { Project } from "@/lib/types";
import { paintBackground, paintPuppet, type Mood } from "@/lib/storybook-art";

function moodFor(text:string):Mood{const s=text.toLowerCase();if(/afraid|scared|sad|lost|dark/.test(s))return"worried";if(/wow|hooray|amazing|excited|race/.test(s))return"excited";if(/wonder|look|discover|question/.test(s))return"curious";return"happy";}
function wrap(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,max:number){const words=text.split(/\s+/);let line="",yy=y;for(const word of words){const next=`${line}${word} `;if(ctx.measureText(next).width>max&&line){ctx.fillText(line.trim(),x,yy);line=`${word} `;yy+=30}else line=next}if(line)ctx.fillText(line.trim(),x,yy)}
function drawScene(project:Project,canvas:HTMLCanvasElement,idx:number,p:number,t:number){const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");const scene=project.scenes[Math.min(idx,project.scenes.length-1)];ctx.save();const zoom=1+.035*Math.sin(p*Math.PI);ctx.translate(canvas.width/2,canvas.height/2);ctx.scale(zoom,zoom);ctx.translate(-canvas.width/2,-canvas.height/2);paintBackground(ctx,canvas.width,canvas.height,t,idx);const ids=new Set(scene.characterIds);let chars=project.characters.filter(c=>!ids.size||ids.has(c.id));if(!chars.length)chars=project.characters.slice(0,2);chars=chars.slice(0,3);const spacing=canvas.width/(chars.length+1);const speaking=!!(scene.dialogue||scene.narration);chars.forEach((c,i)=>{const enter=Math.min(1,p*3);const target=(i+1)*spacing;const start=i%2?-170:canvas.width+170;const x=start+(target-start)*enter;paintPuppet(ctx,c,x,canvas.height*.82,.92,t,i,speaking&&i===Math.floor(t*1.2)%chars.length,moodFor(`${scene.action} ${scene.dialogue} ${scene.narration}`))});ctx.restore();const fade=Math.min(1,p*7)*Math.min(1,(1-p)*7);const caption=(scene.dialogue||scene.narration||"").trim();if(caption){ctx.fillStyle=`rgba(15,23,42,${.62*fade})`;ctx.roundRect(90,canvas.height-105,canvas.width-180,66,18);ctx.fill();ctx.fillStyle=`rgba(255,255,255,${fade})`;ctx.font="600 22px sans-serif";ctx.textAlign="center";wrap(ctx,caption.slice(0,125),canvas.width/2,canvas.height-72,canvas.width-240)}}
function record(project:Project,canvas:HTMLCanvasElement,duration:number,audio:MediaStreamTrack[]=[],progress?:(s:string)=>void){const video=canvas.captureStream(30),stream=new MediaStream([...video.getVideoTracks(),...audio]),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm",rec=new MediaRecorder(stream,{mimeType:mime}),parts:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};const start=performance.now();let raf=0;const frame=()=>{const elapsed=performance.now()-start,ratio=Math.min(.999,elapsed/duration),raw=ratio*project.scenes.length,idx=Math.floor(raw);drawScene(project,canvas,idx,raw-idx,elapsed/1000);if(elapsed<duration)raf=requestAnimationFrame(frame)};return new Promise<Blob>((resolve,reject)=>{rec.onerror=()=>reject(new Error("Video recording failed"));rec.onstop=()=>{cancelAnimationFrame(raf);video.getTracks().forEach(x=>x.stop());resolve(new Blob(parts,{type:mime}))};rec.start(500);raf=requestAnimationFrame(frame);setTimeout(()=>{progress?.("Finalizing storybook video…");if(rec.state!=="inactive")rec.stop()},duration+250)})}
async function device(project:Project,canvas:HTMLCanvasElement,progress?:(s:string)=>void){if(!("speechSynthesis" in window))throw new Error("Narration is not supported on this phone.");const text=project.voiceLines.map(v=>v.text).join(" ")||project.story.fullStory,words=text.trim().split(/\s+/).length,duration=Math.max(8000,words/2.15*1000),u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.94;u.pitch=1.08;progress?.("Animating storybook characters…");speechSynthesis.cancel();speechSynthesis.speak(u);const blob=await record(project,canvas,duration,[],progress);speechSynthesis.cancel();return blob}
export async function renderNarratedVideo(project:Project,canvas:HTMLCanvasElement,progress?:(s:string)=>void){if(!canvas.captureStream||typeof MediaRecorder==="undefined")throw new Error("Video creation is not supported by this browser.");try{progress?.("Preparing free neural narration…");const{predict}=await import("@mintplex-labs/piper-tts-web");const text=project.voiceLines.map(v=>v.text).join(" ")||project.story.fullStory,wav=await predict({text,voiceId:"en_US-hfc_female-medium"}),ac=new AudioContext(),buffer=await ac.decodeAudioData(await wav.arrayBuffer()),source=ac.createBufferSource(),dest=ac.createMediaStreamDestination();source.buffer=buffer;source.connect(dest);progress?.("Animating storybook characters…");source.start();const blob=await record(project,canvas,Math.max(8000,buffer.duration*1000),dest.stream.getAudioTracks(),progress);dest.stream.getTracks().forEach(x=>x.stop());await ac.close();return blob}catch{return device(project,canvas,progress)}}
